version: "3"
services:
  nacos:
    image: nacos/nacos-server:1.4.0
    container_name: nacos
    # 这里是重点
    networks:
      - nacos-mysql
    env_file:
      - ./env/nacos-standlone-mysql.env
    volumes:
      - ./standalone-logs/:/home/nacos/logs
      - ./env/custom.properties:/home/nacos/init.d/custom.properties
    ports:
      - "8848:8848"
      - "9555:9555"
    restart: always
# 这里是重点
networks:
  nacos-mysql:
    external: true
