version: "3"
services:
  eureka-server:
    image:  steeltoeoss/eureka-server
    hostname: eureka-server
    ports:
      - "8761:8761"
    networks:
      - spring-netflix-demo
networks:
  spring-netflix-demo:
    driver: bridge