version: '3.5'
services:
  rmqnamesrv-a:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqnamesrv-a
    ports:
      - 9876:9876
    volumes:
      - /home/windli/docker/logs/nameserver-a:/opt/logs
      - /home/windli/docker/store/nameserver-a:/opt/store
    command: sh mqnamesrv
    networks:
        rmq:
          aliases:
            - rmqnamesrv-a

  rmqnamesrv-b:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqnamesrv-b
    ports:
      - 9877:9876
    volumes:
      - /home/windli/docker/logs/nameserver-b:/opt/logs
      - /home/windli/docker/store/nameserver-b:/opt/store
    command: sh mqnamesrv
    networks:
        rmq:
          aliases:
            - rmqnamesrv-b
            
  rmqnamesrv-c:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqnamesrv-c
    ports:
      - 9878:9876
    volumes:
      - /home/windli/docker/logs/nameserver-a:/opt/logs
      - /home/windli/docker/store/nameserver-a:/opt/store
    command: sh mqnamesrv
    networks:
        rmq:
          aliases:
            - rmqnamesrv-c

  rmqbroker-a:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqbroker-a
    ports:
      - 10912:10912
     # - 10911:10911
    volumes:
      - /home/windli/docker/logs/broker-a:/opt/logs
      - /home/windli/docker/store/broker-a:/opt/store
      - /home/windli/docker/broker-a.conf:/opt/rocketmq-4.3.0/conf/broker.conf 
    environment:
        TZ: Asia/Shanghai
        NAMESRV_ADDR: "rmqnamesrv-a:9876"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms256m -Xmx512m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
      - rmqnamesrv-c:rmqnamesrv-c
    networks:
      rmq:
        aliases:
          - rmqbroker-a
  rmqbroker-a-slave:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqbroker-a-slave
    ports:
      - 11912:11912
      # - 10911:10911
    volumes:
      - /home/windli/docker/logs/broker-a-slave:/opt/logs
      - /home/windli/docker/store/broker-a-slave:/opt/store
      - /home/windli/docker/broker-a-slave.conf:/opt/rocketmq-4.3.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-a:9876"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx512m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
      - rmqnamesrv-c:rmqnamesrv-c
    networks:
      rmq:
        aliases:
          - rmqbroker-a-slave

  rmqbroker-b:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqbroker-b
    ports:
      - 10913:10913
    #  - 10914:10911
    volumes:
      - /home/windli/docker/logs/broker-b:/opt/logs
      - /home/windli/docker/store/broker-b:/opt/store
      - /home/windli/docker/broker-b.conf:/opt/rocketmq-4.3.0/conf/broker.conf 
    environment:
        TZ: Asia/Shanghai
        NAMESRV_ADDR: "rmqnamesrv-b:9877"
        JAVA_OPTS: " -Duser.home=/opt"
        JAVA_OPT_EXT: "-server -Xms256m -Xmx512m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
      - rmqnamesrv-c:rmqnamesrv-c
    networks:
      rmq:
        aliases:
          - rmqbroker-b
  rmqbroker-b-slave:
    image: rocketmqinc/rocketmq:4.3.0
    container_name: rmqbroker-b-slave
    ports:
      - 11913:11913
    #  - 10914:10911
    volumes:
      - /home/windli/docker/logs/broker-b-slave:/opt/logs
      - /home/windli/docker/store/broker-b-slave:/opt/store
      - /home/windli/docker/broker-b-slave.conf:/opt/rocketmq-4.3.0/conf/broker.conf
    environment:
      TZ: Asia/Shanghai
      NAMESRV_ADDR: "rmqnamesrv-b:9877"
      JAVA_OPTS: " -Duser.home=/opt"
      JAVA_OPT_EXT: "-server -Xms256m -Xmx512m -Xmn256m"
    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
    links:
      - rmqnamesrv-a:rmqnamesrv-a
      - rmqnamesrv-b:rmqnamesrv-b
      - rmqnamesrv-c:rmqnamesrv-c
    networks:
      rmq:
        aliases:
          - rmqbroker-b-slave
#  rmqbroker-c:
#    image: rocketmqinc/rocketmq:4.3.0
#    container_name: rmqbroker-c
#    ports:
#      - 10914:10914
#    #  - 10914:10911
#    volumes:
#      - /home/windli/docker/logs/broker-c:/opt/logs
#      - /home/windli/docker/store/broker-c:/opt/store
#      - /home/windli/docker/broker-c.conf:/opt/rocketmq-4.3.0/conf/broker.conf
#    environment:
#        TZ: Asia/Shanghai
#        NAMESRV_ADDR: "rmqnamesrv-c:9878"
#        JAVA_OPTS: " -Duser.home=/opt"
#        JAVA_OPT_EXT: "-server -Xms258m -Xmx512m -Xmn256m"
#    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
#    links:
#      - rmqnamesrv-a:rmqnamesrv-a
#      - rmqnamesrv-b:rmqnamesrv-b
#      - rmqnamesrv-c:rmqnamesrv-c
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-c
#  rmqbroker-c-slave:
#    image: rocketmqinc/rocketmq:4.3.0
#    container_name: rmqbroker-c-slave
#    ports:
#      - 11914:11914
#    #  - 10914:10911
#    volumes:
#      - /home/windli/docker/logs/broker-c-slave:/opt/logs
#      - /home/windli/docker/store/broker-c-slave:/opt/store
#      - /home/windli/docker/broker-c-slave.conf:/opt/rocketmq-4.3.0/conf/broker.conf
#    environment:
#      TZ: Asia/Shanghai
#      NAMESRV_ADDR: "rmqnamesrv-c:9878"
#      JAVA_OPTS: " -Duser.home=/opt"
#      JAVA_OPT_EXT: "-server -Xms256m -Xmx512m -Xmn256m"
#    command: sh mqbroker -c /opt/rocketmq-4.3.0/conf/broker.conf autoCreateTopicEnable=true & diskSpaceWarningLevelRatio=0.98
#    links:
#      - rmqnamesrv-a:rmqnamesrv-a
#      - rmqnamesrv-b:rmqnamesrv-b
#      - rmqnamesrv-c:rmqnamesrv-c
#    networks:
#      rmq:
#        aliases:
#          - rmqbroker-c-slave
  zookeeper:
    image: wurstmeister/zookeeper
    environment:
      JMX: 9000
    ports:
      - "2181:2181"
  rmqconsole:
    image: styletang/rocketmq-console-ng
    container_name: rmqconsole
    ports:
      - 8089:8080
    environment:
        JAVA_OPTS: -Drocketmq.namesrv.addr=rmqnamesrv-a:9876;rmqnamesrv-b:9877;rmqnamesrv-c:9878 -Dcom.rocketmq.sendMessageWithVIPChannel=false
    networks:
      rmq:
        aliases:
          - rmqconsole
networks:
  rmq:
    name: rmq
    driver: bridge