version: '3'
services:
  mysql:
    environment:
      MYSQL_ROOT_PASSWORD: "root"
      MYSQL_USER: 'nacos'
      MYSQL_PASS: 'nacos'
    image: mysql
    restart: always
    # 这里是重点
    networks:
      - nacos-mysql
    volumes:
      - "./db:/var/lib/mysql"
      - "./conf/my.cnf:/etc/my.cnf"
      - "./init:/docker-entrypoint-initdb.d/"
    ports:
      - "3306:3306"
# 这里是重点
networks:
  nacos-mysql:
    external: true